//BEGIN_CONFIG_PARAMS
#define BUNNY_ID_LEN 16
#define ROBOT_ID_LEN 8
#define MAX_ROBOTS 255
#define BUNNY_TABLE_SIZE 300000
#define FUNCTION_SIZE 4000
#define SPEED_LIMIT_SIZE 640
//END_CONFIG_PARAMS
